version: '3.7'

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: PAPER
      VERSION: 1.16.5
      # needed for Paper versions before 1.14
      CONSOLE: "false"
      MEMORY: 3G
      OVERRIDE_OPS: "true"
      OPS: st3ck1
      MOTD: "gemuesekrieg.de Minecraft Server Ga Ming"
    ports:
      - 25565:25565
    volumes:
      - /home/mc:/data
